export const TOPIC_LAST_WILL = "lastWill";
export const TOPIC_OPERATION_STATE_STATUS = "state/status"; // receive current operation state
export const TOPIC_OPERATION_STATE_COMMAND = "state/command"; // query current operation state
export const TOPIC_OPERATION_MODE_STATUS = "mode/status";
export const TOPIC_OPERATION_MODE_COMMAND = "mode/command";
export const TOPIC_WAVE_STATUS = "wave/status";
export const TOPIC_WAVE_COMMAND = "wave/command";
export const TOPIC_PARAMETER_STATUS = "parameter/status";
export const TOPIC_PARAMETER_COMMAND = "parameter/command";
export const TOPIC_CONTROL_ITEM_STATUS = "control_item/status";
export const TOPIC_CONTROL_ITEM_COMMAND = "control_item/command";
export const TOPIC_LOG_STATUS = "log/status";
export const TOPIC_LOG_COMMAND = "log/command";
export const TOPIC_INPUT_STATUS = "input/status";
export const TOPIC_INPUT_COMMAND = "input/command";
export const TOPIC_OUTPUT_STATUS = "output/status";
export const TOPIC_OUTPUT_COMMAND = "output/command";
export const TOPIC_SYSTEM_INFO_STATUS = "system_info/status";
export const TOPIC_SYSTEM_INFO_COMMAND = "system_info/command";
export const TOPIC_SYSTEM_DIAGNOSIS_STATUS = "system_diagnosis/status";
export const TOPIC_SYSTEM_DIAGNOSIS_COMMAND = "system_diagnosis/command";
