export const TOPIC_OPERATION_MODE_STATUS = "operation_mode/status"; // receive current operation mode
export const TOPIC_OPERATION_MODE_COMMAND = "operation_mode/command"; // query current operation mode
export const TOPIC_WAVE_DATA = "wave/data";
export const TOPIC_WAVE_COMMAND = "wave/command";
export const TOPIC_PARAMETER_STATUS = "parameter/status";
export const TOPIC_PARAMETER_COMMAND = "parameter/command";
export const TOPIC_CONTROL_ITEM_STATUS = "control_item/status";
export const TOPIC_CONTROL_ITEM_COMMAND = "control_item/command";
export const TOPIC_LOG_STATUS = "log/status";
export const TOPIC_LOG_COMMAND = "log/command";
export const TOPIC_INPUT_STATUS = "input/status";
export const TOPIC_OUTPUT_STATUS = "output/status";
export const TOPIC_INPUT_COMMAND = "input/command";
export const TOPIC_OUTPUT_COMMAND = "output/command";
